### ISSUE TITLE
Sweep High Gerbers

### ISSUE THREAD

**Issue by telepuzikIsmail** [davidphilipbarr/Sweep#16]
There seems to be something wrong with the gerberfiles for the Sweep High. 
They dont work on JLCPCB, no preview and so on.. or am I doing something wrong?

**Comment by duckyb** [comment]
<img src="https://user-images.githubusercontent.com/27895007/141647421-57a1322f-7930-45f9-b4f4-c899457a5a30.png" width="400">

It might be caused by the new footprint that has some overlaps. The lower two overlaps on the drill layer are reported as errors by the DRC tool in Kicad.
If you still order it the JLC team will still check it for you and let you know if there are issues with your order.

Keep in mind this is a new design and I don't even know if it was ever ordered by anyone before

**Comment by telepuzikIsmail** [comment]
Thanks for the quick answer.
I have order boards now, I'll let you know if it worked out or not.

**Comment by Micosilent** [comment]
I've tried to order Sweep High boards as well, and JLCPCB is complaining about the minimum breakaway tab being 4m
![Screenshot_2021-11-15_10-54-09](https://user-images.githubusercontent.com/18470759/141760902-1e31bddc-f04a-479b-ad56-9fdbfa1caaf4.png)

**Comment by duckyb** [comment]
![image](https://user-images.githubusercontent.com/27895007/141768421-fd6aba2a-08d4-4eec-ad15-935d8fe53710.png)
[sweep-high_229x356mm_for_JLCPCB.zip](https://github.com/davidphilipbarr/Sweep/files/7537976/sweep-high_229x356mm_for_JLCPCB.zip)

On 13/11/2021 @davidphilipbarr shared a gerber for JLC that is missing in this repository. I'm reposting it here for people that might be interested in it.

**Comment by telepuzikIsmail** [comment]
This is what they wrote me in the first mail:

> Sorry that the minimum width of breakaway tab with mouse-bites we recommend is 5mm.
> Sorry that the minimum width of breakaway tab we recommend is 4mm.
![unnamed](https://user-images.githubusercontent.com/86594680/141779723-32439908-c9b2-48b4-8b84-08a5088902ca.png)
![unnamed](https://user-images.githubusercontent.com/86594680/141779790-3e19ae29-bc08-42c5-9316-e94fc5993a51.png)


After replacing the gerbers with those from the post above they wrote:

> the spacing from slot to slot and slot to board edge are too small which will cause the board broken easily,please kindly increase it to 4mm at least.
![unnamed](https://user-images.githubusercontent.com/86594680/141779449-981fafac-5283-4206-8b5b-54922267096d.png)

**Comment by Micosilent** [comment]
The thing is that we literally want the board to break, so the two halves come apart. If you want to wait until I receive mine, I have placed the order and told them to disregard the <4mm breakaway, and will update when the order arrives.

Otherwise just tell them to go ahead with the fab

**Comment by duckyb** [comment]
@Micosilent @telepuzikIsmail the mouse bite footprint is the same used on the Sweep2 PCB and there are no issues with that one. I ordered them before and they didn't ask me anything and the PCBs were ok.

I guess they just want to complain more this week.

**Comment by Micosilent** [comment]
JLCPCB is refusing to make the pcbs with the small mouse bites 😞

**Comment by telepuzikIsmail** [comment]
I wrote them to go ahead and make the pcbs the way they are now and they decided not to answer me so I canceled the order...
I'll try to edit the pcb this weekend and try again.

**Comment by duckyb** [comment]
@telepuzikIsmail @Micosilent I tried to do it for you.

| Current version | My updated fork |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/27895007/141995094-ea3e4031-1171-4f41-91c3-ab4c81d4ff11.png) | ![image](https://user-images.githubusercontent.com/27895007/141994948-a4490922-7f9c-4ea3-826e-b1b155074d54.png) |
| ![image](https://user-images.githubusercontent.com/27895007/141995222-4b6ddae1-5e47-4547-8766-c855b0192232.png) | ![image](https://user-images.githubusercontent.com/27895007/141994045-c73ea5ba-6c59-46e0-977e-fbd9f0d4f8da.png) |

My fork gerber: [sweep-high-gerber.zip](https://github.com/davidphilipbarr/Sweep/files/7546704/sweep-high-gerber.zip) 

Please note that I removed the GND-GND wire that crossed the mouse bite, as it didn't fit through the drill holes. But I don't think it is important as it will be broken off.

Also note that this gerber does not show a preview on JLCPCB, just like the gerber from the current version in this repo.

**Comment by microfortnight** [comment]
JLCPCB accepted my order based on the fork of @duckyb 
Didn't use the linked gerbers because I wanted to remove the crab 😜
I used asukiaaa/gerber_to_order to create the gerbers and the preview on JLCPCB is displayed correctly.

**Comment by duckyb** [comment]
@microfortnight thank you for the feedback! If you could update us once more after receiving the PCBs it would be awesome.
In particular regarding the breakaway tab; if it snaps well, how much clean up is required, possible improvements, etc.

Also nice tip on using that gerber tool. I'll check it out!

**Comment by nodupe** [comment]
I’ve placed the order a few days ago and had the same issue, even after assuring them it was supposed to break, they still complained. Just uploaded the new file now, looking forward to their answer.

**Comment by Narice** [comment]
@microfortnight, did you get the board? I'll probably build one and having some feedback to know if this gerber file worked would be really awesome :grin:

**Comment by microfortnight** [comment]
@duckyb PCBs look fine, didn't build the board yet.
Seperating the halves is easy, one half can be broken up by hand, you will need pliers to separate the tabs from the other half. That's a very minor disadvantage, compared e.g. to the crkbd cherry, where it's possibe to do it using hands only.
Apply a very light sanding and it is good to go :+1:

**Comment by lxhan** [comment]
Hey guys, can someone please explain or show how to plug in switches into sweep high board? I've just received pcb but wanted to double check before soldering, is it ok that mx switches are loose compared to what I saw in @duckyb video on youtube or something wrong with my board?

**Comment by duckyb** [comment]
@lxhan Yes it's somewhat normal. But make sure that you are using 5 pin switches (PCB mount)

**Comment by Narice** [comment]
@microfortnight thanks! that really helps
