### ISSUE TITLE
sweep 2.1 gerbers

### ISSUE THREAD

**Issue by mybigman** [davidphilipbarr/Sweep#17]
gerber zip is missing for 2.1 or do we use the one from 2

thanks

**Comment by Micosilent** [comment]
2.1 is Work in Progress, you can use the gerbers from v2  though :D

**Comment by duckyb** [comment]
The gerber for 2.1 is available if you want to try it!

**Comment by eXsoR65** [comment]
@duckyb looks like the gerber file is not reflecting the change of removing the extra pin on one of the switched on the right half. I tried to generate the gerber files but gave me a warning about filling in. But I'm new to this so not sure if I should or not. Any help on this is appreciated.

**Comment by duckyb** [comment]
@eXsoR65 you can find the updated files on my branch https://github.com/duckyb/Sweep/tree/update-gerbers
I also created #24 to update them here.

**Comment by eXsoR65** [comment]
@mybigman Issue was address so you can close the issue. see PR #24
