### ISSUE TITLE
Sweep 2.1 Changes/Goals

### ISSUE THREAD

**Issue by defiant00** [davidphilipbarr/Sweep#18]
Hi, just wondering if there's a specific issue (or design goal) that the Sweep 2.1 is meant to address?

**Comment by duckyb** [comment]
I can see these differences:

## v2.1 - Changelog
- Better alignment of the micro-controller footprint silkscreen
- Change micro-controller silkscreen from full labeling to minimal
- Move micro-controller footprint away from edge cut (~0.13 mm)
- Connect the two PCBs with mouse-bites away from the micro-controller footprint

**Comment by defiant00** [comment]
Thanks so much for the info, that's quite helpful!
