### ISSUE TITLE
Reset switch part number

### ISSUE THREAD

**Issue by ch604** [davidphilipbarr/Sweep#20]
From the images they appear to be SMD 3x4x2 2 pin pushbuttons, correct?

**Comment by duckyb** [comment]
![image](https://user-images.githubusercontent.com/27895007/142955322-1a83eaf8-99a9-4405-9b2a-8dd58163693b.png)

Documentation: https://omronfs.omron.com/en_US/ecb/products/pdf/en-b3u.pdf

This component is compatible. Part number is **B3U-1000P(M)**
(this is just one of many compatible buttons)

**Comment by duckyb** [comment]
![image](https://user-images.githubusercontent.com/27895007/142956091-57cfd5b8-9499-491f-8aed-b732368edfc7.png)

This is the footprint, for reference

**Comment by ch604** [comment]
Thanks for that pcb breakout and the exact reference part, looks like the piece I selected will fit!
