### ISSUE TITLE
Sweep High Half-Swept

### ISSUE THREAD

**Issue by hadaad** [davidphilipbarr/Sweep#25]
Do you think it would be possible to create a half-swept sweep high?

**Comment by duckyb** [comment]
I think the naming system should be revised 😂

**Comment by athul** [comment]
Would be great if you could make this. It's relatively hard to get my hands on choc switches but it's really easy to get mx type switches😅😅

**Comment by duckyb** [comment]
Well, it exists and it's called **Sweep High M**
