### ISSUE TITLE
feature request: choc V2 supported board 

### ISSUE THREAD

**Issue by deggers** [davidphilipbarr/Sweep#3]
Hey,
Thank you soo much for your work creating a proMicro compatible ferris :) 

I wonder if you have any plans in creating a sweep V2 with mx spacing and choc V2 support? The corne light looks sooo cool with mt3 on the choc V2 - but I love the ferris layout .. what do you think?

**Comment by davidphilipbarr** [comment]
i nearly have an mx spaced  board ready, i'm just finalising the footprint. mx/chocv1/chocv2 any others? alps?

**Comment by amcguire2** [comment]
> i nearly have an mx spaced board ready, i'm just finalising the footprint. mx/chocv1/chocv2 any others? alps?

Thank you for working on this, I can't wait !

**Comment by bazitov** [comment]
> i nearly have an mx spaced board ready, i'm just finalising the footprint. mx/chocv1/chocv2 any others? alps?

How do you look at the idea to have the hotswap and none-hotswap choc PCB like Architeuthis dux?

**Comment by duckyb** [comment]
This issue was solved with the introduction of the **Sweep High**, it should be closed.
