### ISSUE TITLE
Question: Difference between High and High M

### ISSUE THREAD

**Issue by isavcic** [davidphilipbarr/Sweep#30]
Hello,

I apologize if this question is an obvious one, but I'm about to embark on building an MX-version board for myself. Which version of High should I use? What is the difference?

Thanks!

**Comment by duckyb** [comment]
High M is the reversible version of the high. Like sweep2 vs sweep half swept.
You can use both but the high is more tested

**Comment by isavcic** [comment]
In which way "reversible", as in the board can be on the bottom side of the board?

**Comment by duckyb** [comment]
@isavcic yes. Reversible means that the same PCB is used for left and right side. In the regular sweep high you have a dedicated PCB for each side.
This is just a minor difference, both devices function the same.

**Comment by isavcic** [comment]
@duckyb Thanks!
