### ISSUE TITLE
Comaptibility with Pro Micro with USB-C port?

### ISSUE THREAD

**Issue by Sono-Gomorrha** [davidphilipbarr/Sweep#31]
I was wondering if the 2.1 PCB would be compatible with Pro Micros with USB C port or only with Micro USB. 
I know this might sound stupid, but I am somewhat new to building these and some of the listings I saw the USB C version is listed longer (2mm difference) and the spacing / sizing of the pinholes looks a little different. 

This is an [example](https://www.aliexpress.com/item/32768308647.html?spm=a2g0o.productlist.0.0.437b6e79PCNYt7&algo_pvid=b8e888df-a903-421a-818e-e77b4d27c868&algo_exp_id=b8e888df-a903-421a-818e-e77b4d27c868-0&pdp_ext_f=%7B%22sku_id%22%3A%2212000024349272661%22%7D&pdp_pi=-1%3B5.0%3B-1%3BEUR+2.27%40salePrice%3BEUR%3Bsearch-mainSearch) and here is [another](https://www.aliexpress.com/item/1005001621886380.html?spm=a2g0o.productlist.0.0.437b6e79PCNYt7&algo_pvid=b8e888df-a903-421a-818e-e77b4d27c868&algo_exp_id=b8e888df-a903-421a-818e-e77b4d27c868-1&pdp_ext_f=%7B%22sku_id%22%3A%2212000016846658600%22%7D&pdp_pi=-1%3B5.0%3B-1%3BEUR+2.15%40salePrice%3BEUR%3Bsearch-mainSearch).

**Comment by duckyb** [comment]
It's compatible
