### ISSUE TITLE
3D printable top plate for the Sweep High?

### ISSUE THREAD

**Issue by mrtnee** [davidphilipbarr/Sweep#32]
Hi, how would one go about creating the 3d printable file for the plate? I know there is an .svg and an .dxf file. I tried using those to create a 3d file but it seems that the two files aren't compatible with the modeling software.

Could you also tell me how you created the .svg and .dxf file?

**Comment by Sono-Gomorrha** [comment]
What kind of software did you use? I had good results with FreeCAD when working with dxf files.

**Comment by duckyb** [comment]
Closed for inactivity. Feel free to reopen/comment if needed.
