### ISSUE TITLE
Feature request: hot swap socket support

### ISSUE THREAD

**Issue by dlip** [davidphilipbarr/Sweep#34]
Would you be able to support hot swap sockets?

**Comment by duckyb** [comment]
A problem with hot swap sockets is that the switches will be unstable unless you also have a plate to hold the switches. This has been discussed before in discord and some people have already tried to edit the PCB but I've yet to see a hotswap sweep

**Comment by elisiano** [comment]
ooohhh the millmax support would be awesome, as it would be a lower profile than the hot swap socket!

**Comment by duckyb** [comment]
Sweep v2.2 now supports millmax sockets.
