### ISSUE TITLE
JLCPCB says "Panel by Customer" for Sweep 2.1

### ISSUE THREAD

**Issue by lzhang10** [davidphilipbarr/Sweep#35]
I uploaded the Sweep 2.1 file to JLCPCB. When I choose Different Design to be 2 I can not pick "Single PCB" as Delivery Format. The other options are "Panel by Customer" and "Panel by JLCPCB".

Is it safe to set Different Design to be 1 so that I can use "Single PCB" as Delivery Format?

**Comment by duckyb** [comment]
You can try and do that but they might stop your order and tell you "This is not a single design". Because the two PCBs don't have an electrical connection between them and they have different silkscreens etc.

I would suggest ordering a Sweep half-swept instead, if you want to be sure.

**Comment by lzhang10** [comment]
Thanks for the explanation. I chose 1 design with Single PCB delivery and my order passed review.
