### ISSUE TITLE
there is missing components.

### ISSUE THREAD

**Issue by partrita** [davidphilipbarr/Sweep#36]
It just so obvious but

please add 1x TRS cable(3.5mm) and 2x TRS jack(PJ-320A)

thanks.

**Comment by duckyb** [comment]
Thank you for reporting this issue, I have fixed it.
But take care; the cable you get **MUST be a TRRS** cable! (It should have 3 black rings on it)

**Comment by partrita** [comment]
> 

Oh, Thanks :)
