### ISSUE TITLE
[Sweep v2] MCU pads very close to keyboard edge

### ISSUE THREAD

**Issue by duckyb** [davidphilipbarr/Sweep#4]
Hi, I printed the latest version of the Sweep v2 from JLCPCB and I noticed a small issue with the design.
First of all, the fact that the PCBs are conjoined leaves two small bumps on the inner edge of the board, which can be sanded but might be risky with it being so close to the MCU's pads.
And second, the pads are very very close to the edge, nothing to worry about but it would be nice to have a slight margin between the MCU's pads and the edge of the PCB.

Both these issues could be fixed by adding a .5mm - 1mm margin to the inner edge of the PCB.

![image](https://user-images.githubusercontent.com/27895007/129099677-49e33d51-7724-449b-89ab-5ea23e61d17b.png)

![image](https://user-images.githubusercontent.com/27895007/129099713-36cada51-db37-4f15-be85-f4b7680f0d50.png)

**Comment by davidphilipbarr** [comment]
I think this fixed in the dev branch, the holes are very close to the edge still, but less so. 
![Screenshot from 2021-09-10 09-54-29](https://user-images.githubusercontent.com/93874/132835286-7b04e15a-1c59-4fd5-a4be-2dc727200355.png)

**Comment by duckyb** [comment]
It should be enough!
