### ISSUE TITLE
Support for BlackPill (STM32F4X1)

### ISSUE THREAD

**Issue by matru** [davidphilipbarr/Sweep#41]
Will this be available in the future, it is a bit wider and lengthier compared to the ProMicro/Elite-C.

STM32F4X1, it goes by BlackPill too, is a much more powerful MCU, USB-C, open-source (https://github.com/WeActTC/MiniSTM32F4x1), it is officially manufactured by WeAct at this moment, and it is also priced very low at $7 + shipping, it was even lower I believe. Of course it is officially QMK supported.

Would be awesome to see this one more widespread.

**Comment by duckyb** [comment]
> "You can get usb c promicros now which was the big sell of the black pill originally, we don't need the additional power or memory." - @davidphilipbarr 

It would be nice to support everything but that would require having a large amount of different sweep versions. After supporting the blackpill for choc people would ask to also support it for mx or vice versa. Same goes for all other sweep versions.

So it won't be done, but you are welcome to fork the repository and create your own version with BlackPill support ✌🏻
