### ISSUE TITLE
Which is the behaviour of the on/off switch?

### ISSUE THREAD

**Issue by leiserfg** [davidphilipbarr/Sweep#43]
I got a preassembled sweep with nice!nanos but it seems like the switches don't turn it off, is that the intended behaviour or is it incorrectly mounted?

**Comment by davidphilipbarr** [comment]
sounds like something is wrong there, do you have some photos of the
switch/battery connection?

**Comment by leiserfg** [comment]
![IMG_20220324_074833](https://user-images.githubusercontent.com/2947276/159858672-c77ecfa6-306e-453c-b6f2-50a0323cbf0e.jpg)
![IMG_20220324_074739](https://user-images.githubusercontent.com/2947276/159858676-d984f29e-d1bb-4bbf-b458-ebc0c6200b41.jpg)

**Comment by leiserfg** [comment]
![IMG_20220324_075007](https://user-images.githubusercontent.com/2947276/159858905-4ea542ce-785a-4e0c-b30d-3c9fa25ccef7.jpg)

**Comment by leiserfg** [comment]
I took the picture with the switch on and off but I can type with it no matter what

**Comment by duckyb** [comment]
@leiserfg How can the switch do anything if the battery is directly connected to the nice!nano?
In order for it to work, the battery must be connected to the sweep PCB.

![battery-schematic-sweep](https://user-images.githubusercontent.com/27895007/159889092-45c7742d-ac0d-4ee0-a95b-68b75a6535c2.jpg)

**Comment by duckyb** [comment]
In case you don't have the tools to fix it, I recommend using these settings in your cradio.conf

```py
# enable deep sleep support
CONFIG_ZMK_SLEEP=y

# the keyboard disconnects from bluetooth.
# uses very little power, but it may take
# a few seconds to reconnect after waking.
# 1.800.000 ms = 30 minutes
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
```
(adjust timeout value according to your preference)

**Comment by leiserfg** [comment]
Thanks a lot, I supposed it was not well wired but didn't know the correct way to do it, I'll recompile the firmware that way and try to rewire it once I get a good iron.
