### ISSUE TITLE
[Bling Mx] Artifact left on bottom plate

### ISSUE THREAD

**Issue by zachatttack** [davidphilipbarr/Sweep#44]
JLCPCB informed me that this artifact was left on the gerber file, and wanted to know if it should be deleted before proceeding.

![image](https://user-images.githubusercontent.com/34082551/160520171-cb20e68e-f76f-4e32-93cd-f7e5f823c2ff.png)

**Comment by duckyb** [comment]
@zachatttack yeah, it was used for alignment when designing the puck cutout. I will remove it and update the gerber. Thanks for reporting.

**Comment by duckyb** [comment]
Fixed in [039183f](https://github.com/davidphilipbarr/Sweep/commit/039183f5cfd70f759bea55cf093227618b1d3112)
