### ISSUE TITLE
Sweep2 vs Sweep Bling MX

### ISSUE THREAD

**Issue by p0da** [davidphilipbarr/Sweep#45]
Just looking for a quick clarification on which type I should build as while the Sweep2 is currently recommended, the Sweep Bling MX seems to be just an overall better version of the Sweep2. Are there any drawbacks to the Bling MX that the 2 doesn't have aside from what is listed on the comparison chart? Thanks for the help, kinda new to the space.

**Comment by duckyb** [comment]
![image](https://user-images.githubusercontent.com/27895007/161163734-fb8b15c2-89ed-4dea-9686-03aa31b0c8ca.png)

The main difference is that one is for choc switches, the other is for MX switches.

**Comment by p0da** [comment]
That clears up my question perfectly, thanks for the help. And that chart is really useful might want to put it on the README.
