### ISSUE TITLE
Reset button for the compact low version

### ISSUE THREAD

**Issue by riveraletelier** [davidphilipbarr/Sweep#47]
First, thanks for putting all of this together.

There is a small issue with the description. It recommends the Omron B3U-1000P(M) for the reset button. It works well, expect for the compact low version that is designed for a through hole button. It would seem that the Apem MJTP1243 button would work, but I haven't tried it yet. Here is a link with to the datasheet in Digikey:
https://media.digikey.com/pdf/Data%20Sheets/APEM%20Components%20PDFs/MJTP%20Series-6MM.pdf

**Comment by duckyb** [comment]
Thanks for reporting this issue. I will replace the footprint on the compact low to use the `Omron B3U-1000P(M)` component instead.

**Comment by riveraletelier** [comment]
That would be great, thanks!

**Comment by duckyb** [comment]
Fixed and merged
