### ISSUE TITLE
Sweep High Plated Slot Width

### ISSUE THREAD

**Issue by ballin2much** [davidphilipbarr/Sweep#48]
Trying to purchase sweep high from JLBPC and they are saying the following:
"the minimum width of plated slot need to be 0.5mm or more, could we enlarge the width of 0.3mm and 0.4mm slots to 0.5mm?"

<img src="https://user-images.githubusercontent.com/38084637/164946515-91058d71-5e64-441b-9d53-620da9fb48ab.png" width="400">

Very unfamiliar with PCB design so I'm unsure if this is an issue with the gerber file, if I did something wrong, or if I just need to tell them that it is fine to enlarge.

**Comment by duckyb** [comment]
@ballin2much Reply:

```
Yes, you can enlarge the slots to 0.5mm.
Thanks.
```

This is the second time they complain, we should change the footprint.

**Comment by ballin2much** [comment]
Thanks for the quick reply. Appreciate all the documentation/tutorials.

**Comment by duckyb** [comment]
![image](https://user-images.githubusercontent.com/27895007/164950662-3742703c-d552-41ca-9ef3-a427e535d6f2.png)

Updated the silk screen and enlarged the slots

**Comment by duckyb** [comment]
This issue is now fixed: https://github.com/davidphilipbarr/Sweep/commit/f87ba64e6f716add1bc7cf43377e1d57bf9c240c
The gerber is updated to the new version.
