### ISSUE TITLE
[Sweep v2] Peripheral side not sending inputs

### ISSUE THREAD

**Issue by rodrigocam** [davidphilipbarr/Sweep#55]
Hey, I build a sweep keyboard v2 but it only works the half connected to the USB. I have a TRRS cable but it didn't work. I have tested the continuity of the holes of the TRRS jack in the PCB and I found a strange behavior, the two holes in the picture below give continuity, is it right?

![front_c](https://user-images.githubusercontent.com/12930004/169601031-59f00873-a976-42be-a0e5-1fa0c4a3313e.png)

**Comment by davidphilipbarr** [comment]
They should both be gnd, so that is normal. Do you have some pics of the
top and bottom of your board?

**Comment by rodrigocam** [comment]
Yes, the one assembled and the other factory new:

![image](https://user-images.githubusercontent.com/12930004/169604067-29d61edb-1f06-4727-8f65-b98f368f815e.png)
![image](https://user-images.githubusercontent.com/12930004/169604094-af776fbb-ee03-4aab-bb7d-c1b415da69ec.png)

![image](https://user-images.githubusercontent.com/12930004/169604111-7698f1f5-46ba-4926-b19f-437e6e6695a4.png)
![image](https://user-images.githubusercontent.com/12930004/169604133-1fb220ac-d1d1-4603-85a3-fac351dc7a1e.png)

**Comment by rodrigocam** [comment]
1. Test that all pins on the VCC net are connected ✅
2. Test that all pins on the switch 18 net are connected ✅

**Comment by duckyb** [comment]
> 1. Test that all pins on the VCC net are connected ✅
> 2. Test that all pins on the switch 18 net are connected ✅

Then it shouldn't be a hardware issue 🤔

**Comment by rodrigocam** [comment]
Is it possible I'm flashing the wrong firmware? I'm using this one https://config.qmk.fm/#/ferris/sweep/LAYOUT_split_3x5_2

**Comment by duckyb** [comment]
@rodrigocam try to flash eeprom right/left on your respective micro controllers
`QMK Toolbox > Tools > EEPROM > Set L/R`

**Comment by daskygit** [comment]
You're likely going to want to compile firmware with a option enabled.

Try add `#define SPLIT_USB_DETECT` to your config.h and flashing both sides.

This changes the USB detection so it doesn't use VBUS sensing which can be a problem with some promicros.

**Comment by rsteube** [comment]
Second on the [SPLIT_USB_DETECT](https://github.com/rsteube/qmk-keymap/blob/master/ferris-rgaertner/config.h#L8). Coincidentally also had the issue today where it seems the promicro always tried to be master.
I think sth. is up with  [J1](https://docs.splitkb.com/hc/en-us/articles/360010588860-Only-one-half-of-my-keyboard-works-at-a-time-but-not-when-they-are-both-connected) which apparently is bridged although the pads are clean.
Adding the config fixed it.

**Comment by rodrigocam** [comment]
> You're likely going to want to compile firmware with a option enabled.
> 
> Try add `#define SPLIT_USB_DETECT` to your config.h and flashing both sides.
> 
> This changes the USB detection so it doesn't use VBUS sensing which can be a problem with some promicros.

This worked like a charm, thanks! 👍

**Comment by mladedav** [comment]
I've just run into the same issue. Is there a downside to using this option or can I try and add this option to the qmk firmware?

**Comment by cgahr** [comment]
I have the same issue. However, for me, `#define SPLIT_USB_DETECT` does not solve the problem. 
VCC net and switch 18 net are fine for me too. 

Any help would be appreciated!

**Comment by duckyb** [comment]
> I have the same issue. However, for me, `#define SPLIT_USB_DETECT` does not solve the problem. VCC net and switch 18 net are fine for me too.
> 
> Any help would be appreciated!

1. Make sure you are using a TRRS cable and not a TRS.
2. Connect the cable and test net 18 with the cable connected. Also test that parts that should be on different nets are not connected (shorts).

**Comment by cgahr** [comment]
> > I have the same issue. However, for me, `#define SPLIT_USB_DETECT` does not solve the problem. VCC net and switch 18 net are fine for me too.
> > Any help would be appreciated!
> 
>     1. Make sure you are using a TRRS cable and not a TRS.
> 
>     2. Connect the cable and test net 18 with the cable connected. Also test that parts that should be on different nets are not connected (shorts).

1. I'm using a TRRS cable
2. VCC and net 18 both look good, with cable connected
3. I couldn't find any short 
4. each half individually is working fine



I compile with the following command
```
qmk compile -kb ferris/sweep -km ryoku -e MAKECMDGOALS=uf2-split-left -e TARGET=sweep_ryoku_left
qmk compile -kb ferris/sweep -km ryoku -e MAKECMDGOALS=uf2-split-right -e TARGET=sweep_ryoku_right
```
and 
```
# rules.mk
CONVERT_TO=elite_pi
SPLIT_KEYBOARD = yes
CONSOLE_ENABLE = yes
```
```
\\ config.h
#define SPLIT_USB_DETECT
#define SERIAL_DEBUG
```

When I run `qmk console` and conntect my keyboard, I get:
```
DPB:Ferris sweep:1: SPLIT: receiving handshake failed
DPB:Ferris sweep:1: SPLIT: receiving handshake failed
DPB:Ferris sweep:1: SPLIT: receiving handshake failed
DPB:Ferris sweep:1: Failed to execute slave_matrix
DPB:Ferris sweep:1: Target disconnected, throttling connection attempts
DPB:Ferris sweep:1: SPLIT: receiving handshake fail
```

**Comment by duckyb** [comment]
@cgahr I would recommend taking this to [QMK's discord chat](https://discord.gg/Uq7gcHh) as I don't know how to help you and not many people will be looking at this page.

**Comment by cgahr** [comment]
Thank you anyways :)
