### ISSUE TITLE
Sweep Compact Low  (additional keys)

### ISSUE THREAD

**Issue by zaddok** [davidphilipbarr/Sweep#56]
This looks like an amazing project, thanks so much for this work! 

It looks like the “Sweep Compact Low - The only version that supports Choc minis.” Would be my ideal keyboard, but with an couple of extra custom keys. I type with some other languages that at have some additional needs. 

Maybe three keys added on each end (6 keys), or maybe two keys added for each thumb (4 keys)

I was thinking of trying to learn how to to do that, but I wanted to check if anyone had done anything like this before.

**Comment by duckyb** [comment]
If you want to **not** use diodes / switch matrix you can only have 1 key per switch pin. This puts a limit of 17 keys per side with a pro-micro. You can get extra keys only if you use a switch matrix with diodes, or if you use an elite-c and make use of the extra pins.

**Comment by davidphilipbarr** [comment]
The sweeeeep uses the extra pins from the elite-c for leds and a screen:

https://github.com/sadekbaroudi/sweeeeep

the cantor uses a black pill to get the extra pins:

https://github.com/diepala/cantor

They might be of interest?
