### ISSUE TITLE
[Sweep v2] Too many slots / Extra drill time fee

### ISSUE THREAD

**Issue by muk343** [davidphilipbarr/Sweep#58]
When I upload the sweep2.2 related gerber file to jlc with the recommended config, they complained about having too many small slots and asked me to pay extra. Is it an issue which many people have faced? 

<img width="943" alt="Screen Shot 2022-05-28 at 1 29 24 AM" src="https://user-images.githubusercontent.com/4137169/170817609-91907614-7238-4f0b-ace7-00ae0d6a9ee6.png">

**Comment by duckyb** [comment]
This is not common from my experience. You got unlucky with the engineer that checked it, maybe they were in a bad mood.

Try to order on a different day, or try PCBway instead
