### ISSUE TITLE
Ferris sweep on nRFMicro

### ISSUE THREAD

**Issue by conceptroot** [davidphilipbarr/Sweep#61]
Hi guys. 
Is it possible to use nRFMicro instead of Nice!Nano in Ferris Sweep?
It is almost impossible to get Nice!Nano in my country.

If ferris sweep runs on nRFMicro, it would be great to indicate it in documentation.

**Comment by GerardoNevarez** [comment]
there's no reason why it should not work... just need to make sure the headers are slightly more open, in case the eByte module bumps into them.

See the module on top, and how close the headers will be with the nrfmicro upside down.  just open them a bit to the sides.  [nrfmicro with shield removed ](https://user-images.githubusercontent.com/852547/136052828-7e8c5e5a-bf60-4805-b5f9-ffaaf6725221.jpg)

**Comment by duckyb** [comment]
| header | pcb clearance |
| --- | --- |
| ![ZVE01864 (Medium)](https://user-images.githubusercontent.com/27895007/189504293-3924d5a7-90a2-45b4-8553-f43a0d5c62cd.jpg) | ![image](https://user-images.githubusercontent.com/27895007/189504329-fda7457d-da15-4735-8318-71add3458999.png) |

**Comment by conceptroot** [comment]
Thanks for replies guys.
It should work I guess. I asked a guy ufan (https://github.com/ufan/sweepro-ce), and he has regular sweep on nRFMicro.
Here is a picture of regular sweep on nRFMicro:
![image](https://user-images.githubusercontent.com/14927755/189526611-e68537fc-7539-4193-9b82-921e29e0bf62.png)

I ordered all PCBs in JLCPCB and in couple of month I'm gonna try this build (nRFMicro on Sweep LP). 
I'll let you know if it works.

**Comment by duckyb** [comment]
@conceptroot good luck! 🍀

**Comment by julientaq** [comment]
hey @conceptroot did you ended up building it? 

I have some nrf and i’m curious about your build.
