### ISSUE TITLE
Question: Why are the switch holes and solder pads on the Sweep Bling MX rotated upside-down

### ISSUE THREAD

**Issue by smoky19x** [davidphilipbarr/Sweep#64]
Hello,

i wonder why the switch holes and solder pads on the Sweep Bling MX are rotated upside-down. What is the reason for this? The space on the PCB should be enough to align it the "normal" way around, or?

**Comment by duckyb** [comment]
It's better to have south facing switches when LEDs are not involved. North facing switches can cause interference with Cherry profile keycaps. (The keycap hits the housing of the switch on the downstroke)

**Comment by smoky19x** [comment]
OK, thanks for the explanation.
