### ISSUE TITLE
Add switch plate and bottom plate for the Sweep High M

### ISSUE THREAD

**Issue by isacben** [davidphilipbarr/Sweep#66]
Hi,

It would be nice to have switch and bottom plates for the Sweep High M version.

The switch plate would be specially important because the Sweep High M version requires Kailh switches with no alignment pins, which makes it difficult to solder them aligned.

Thanks!

**Comment by duckyb** [comment]
I think the bling mx plate might be compatible with it

**Comment by isacben** [comment]
Thanks, Duccio,

I was wondering about that, and I printed both PCBs on paper. It looks aligned, but I cannot confirm that it works. Would have to order the PCBs.

**Comment by duckyb** [comment]
The switch plate will work. The only problem is that it will cover the reset button location.
The bottom plate PCB will not work with it because the main PCB is missing the holes for mounting hardware.

If someone wants to add those holes in the correct location feel free to submit a pull request.

**Comment by isacben** [comment]
Thanks!
