### ISSUE TITLE
Where to source batteries?

### ISSUE THREAD

**Issue by JezThePhilo** [davidphilipbarr/Sweep#68]
Any info on what kind of batteries should we use? The ones listed in desc of the YT video are not on Ebay anymore :/

**Comment by zaddok** [comment]
The numbers for thus type of battery are simply the height and width and length of the battery. If you choose a different number, inside the exact same type of battery, it’ll just be a different size and hold more or less charge depending on the size you selected.

**Comment by duckyb** [comment]
These work fine in my experience https://aliexpress.com/item/4001104720491.html
