### ISSUE TITLE
Sweep Half Swept - both sides show 'place MCU with components facing down'

### ISSUE THREAD

**Issue by anahodil** [davidphilipbarr/Sweep#71]
As it says in the title, both sides of the Sweep Half Swept say to place the MCU with components facing down. I was under the impression that once side (from what I have seen in videos, the right side) should have the components facing up. Does anyone know if what the board says is correct, and that both sides should be components down?

<img width="429" alt="image" src="https://user-images.githubusercontent.com/54943469/233844607-5b3de7f6-fdd0-4f9d-bc02-242013d3024e.png">
<img width="291" alt="image" src="https://user-images.githubusercontent.com/54943469/233844621-9d99976c-17c9-478f-b21a-31124b525b91.png">

**Comment by duckyb** [comment]
Yes, follow the instructions on the PCB.
The version that had one facing up has been archived. On all current sweep versions both controllers are face down.
