### ISSUE TITLE
Is this keyboard supposed to work plugged in to either side?

### ISSUE THREAD

**Issue by jonathanhirz** [davidphilipbarr/Sweep#72]
Hi, sorry for the newbie question. When I have the usb plugged into the right side of this keyboard (pro micro boards), I get key presses from both sides. If I plug into the left side, I only get keypresses from the left side. Is this supposed to work this way, or should it be able to be plugged in either way? I did set handedness, and when both sides are working I see the correct keys coming through. 

LED colors are odd two, left always lights up red, right is green, no matter which one is plugged into usb.

Thanks.

**Comment by duckyb** [comment]
With handedness setup correctly you should be able to plug in on either side.

**Comment by jonathanhirz** [comment]
Alright thanks, I must have something wrong somewhere then.
