### ISSUE TITLE
Is there any top plate for the sweep LP?

### ISSUE THREAD

**Issue by jittapont** [davidphilipbarr/Sweep#76]
Hi,
I want to know if there is any top plate for the choc switches to sit in for sweep LP?
Thanks a lot

**Comment by duckyb** [comment]
There is not

**Comment by DusanLesan** [comment]
@duckyb Can this be reopened as feature request? I have some issues with lose hotswaps on my Sweep Bling LP so I would like to get a gerber file to have FR4 top plates created

**Comment by duckyb** [comment]
@DusanLesan Feel free to open it as a new issue and reference this one in the description
