### ISSUE TITLE
Short at TRRS jack 

### ISSUE THREAD

**Issue by cgahr** [davidphilipbarr/Sweep#78]
In my PCB, at the TRRS jack, there is a short between the following two connectors:
![Screenshot from 2023-10-08 22-15-23](https://github.com/davidphilipbarr/Sweep/assets/26804763/9e2e1679-89b8-4de8-adbf-6b5cb41b4759)

Is this correct?

EDIT:
also, looking at the PCB schematics in more detail, it looks like the `S gnd` (the bottom, single one) is connected to nothing?

**Comment by duckyb** [comment]
Yes this is normal.
