### ISSUE TITLE
Sweep High M variant has silkscreen on the microcontroller contacts preventing soldering

### ISSUE THREAD

**Issue by eallenwright** [davidphilipbarr/Sweep#81]
Sweep High M variant has silkscreen on the microcontroller contacts preventing soldering. I believe the intent is to solder the microcontroller on the right half face down, but still on the top of the board. This is currently not possible due to the silkscreen preventing solder from making a proper contact. I think it's still possible to use this design by letting solder flow down those pins. But this is substandard and (I assume) not the intent of the design. This issue only affects the right half of the board, as the left half has contacts on the bottom that do not have silkscreen covering them. 

I would suggest updating the file to remove the silkscreen from both sides of the microcontroller contacts.

![sweep](https://github.com/davidphilipbarr/Sweep/assets/110061846/0fc952f3-c83d-4620-a443-6420aea1fda9)

![Screenshot_92](https://github.com/davidphilipbarr/Sweep/assets/110061846/d4e9dfde-8010-49ab-83d5-aa6b07678728)
 microcontroller contacts preventing soldering.

**Comment by lpanebr** [comment]
good to know!

If I'm not mistaken you can prevent this kind of problems by 
 - checking the `Subtract soldermask from silkscreen layer` option 

on the `plot dialog`:

![image](https://github.com/davidphilipbarr/Sweep/assets/129185/e29cd6bb-897f-45a3-946d-a93bc5a37a40)
