### ISSUE TITLE
Question; What type/size of Mill-Max Hotswap Sockets?

### ISSUE THREAD

**Issue by Vartroc** [davidphilipbarr/Sweep#85]
Hello,
I was just browsing and searching some materials, when the question arose what type/size of Mill-Max Hotswap Sockets would fit. Maybe I just didn't read carefully enough (I tried) but I can't seem to find any information about that.

I would be delighted if anyone could help me.

**Comment by duckyb** [comment]
If you are planning for hotswap why don't you build a sweep bling instead?

**Comment by Vartroc** [comment]
You are totally right. I was focusing so hard on trying to find the right Mill-Max Socket, that lost my view of the bigger picture...

**Comment by Vartroc** [comment]
Just being curious tho, why is there even the option for a Hotswap Sweep if the Bling exists?

**Comment by duckyb** [comment]
> Just being curious tho, why is there even the option for a Hotswap Sweep if the Bling exists?

You mean why is there an option to add millmax sockets to any other sweep? It's because:

1. That option came before the sweep bling was designed
2. To help people that already have a sweep and would like to try hotswap on a budget
