### ISSUE TITLE
When I connect them together the sweep isn't detected by laptop

### ISSUE THREAD

**Issue by GregePorter** [davidphilipbarr/Sweep#88]
I was able to get the sweep running just fine but it seems like all of a sudden it stopped working. 

After some troubleshooting, it seems like the keyboard halves are able to be detected individually by computers and I can flash them but when I connect them together the combined keyboard isn't detected by the computer.

I tried a new cable too. Do you have any ideas about how to troubleshoot that? Should I replace the TRRS Jack? 

Thanks!

Update:

Huzzah! It was indeed one or both of the jacks. I kinda did it blindly though. Do you know how I would be able to confirm that it was that using a multimeter?

**Comment by duckyb** [comment]
> Do you know how I would be able to confirm that it was that using a multimeter?

It's more likely that it was a soldering issue rather than a faulty TRRS Jack. But you could test them by connecting two jacks with a cable and checking the continuity between the legs of the Jacks.
